name: Multi-Stage Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:  
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build
      run: mvn clean install

    - name: Set Release Version
      run: echo "RELEASE_VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: target/
  tag:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set Release Version
      run: echo "RELEASE_VERSION=$(date +'%Y%m%d%H%M%S')" > env_file.txt
    - name: Use Release Version
      run: echo "Release version is $RELEASE_VERSION"
      env:
        RELEASE_VERSION: $(cat env_file.txt)
    - name: Tag Repository
      run: |
        git tag $RELEASE_VERSION
        git push origin $RELEASE_VERSION

  deploy_dev:
    runs-on: ubuntu-latest
    needs: tag

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: java-app
        path: target/

    - name: Deploy to Dev
      run: echo "Deploying to Dev environment"

  deploy_qa:
    runs-on: ubuntu-latest
    needs: deploy_dev

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: java-app
        path: target/

    - name: Deploy to QA
      run: echo "Deploying to QA environment"

  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy_qa

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: java-app
        path: target/

    - name: Deploy to Prod
      run: echo "Deploying to Prod environment"


