name: Multi-Stage Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build
      run: mvn clean install

    - name: Set Release Version
      run: echo "RELEASE_VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: target/

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: java-app
        path: target/

    - name: Deploy to Dev
      run: echo "Deploying to Dev environment"

  deploy_qa:
    runs-on: ubuntu-latest
    needs: deploy_dev

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: java-app
        path: target/

    - name: Deploy to QA
      run: echo "Deploying to QA environment"

  deploy_prod:
    runs-on: ubuntu-latest
    needs: approve_prod

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: java-app
        path: target/

    - name: Deploy to Prod
      run: echo "Deploying to Prod environment"

  approve_prod:
    runs-on: ubuntu-latest
    needs: deploy_qa
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Request Manual Approval
      uses: actions/github-script@v6
      with:
        script: |
          const { data: pullRequest } = await github.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: 'main',
            base: 'main',
            state: 'open',
          });
          
          if (pullRequest.length === 0) {
            console.error('No open pull requests found for the main branch.');
            process.exit(1);
          }
          
          const response = await github.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pullRequest[0].number,
            event: 'APPROVE',
          });
          console.log(response.data);

