name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'    
        options:
          - 'dev'
          - 'QA'
          - 'Prod'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Environment
        run: echo "Setting up environment=${{ github.event.inputs.environment }}"
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}

  deploy-development:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'dev'

    steps:
      - name: Deploy to Development
        run: echo "Deploying to development..."

  deploy-qa:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'QA'

    steps:
      - name: Deploy to QA
        run: echo "Deploying to QA..."

  deploy-production:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'Prod'

    steps:
      - name: Deploy to Production
        run: echo "Deploying to production..."
