name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        options:
          - 'dev'
          - 'QA'
          - 'Prod'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Chosen Environment
        run: |
          if [ "${{ github.event.inputs.environment }}" == "development" ]; then
            echo "Deploying to development..."
            # Add your deployment logic for the development environment
          elif [ "${{ github.event.inputs.environment }}" == "qa" ]; then
            echo "Deploying to QA..."
            # Add your deployment logic for the QA environment
          elif [ "${{ github.event.inputs.environment }}" == "production" ]; then
            echo "Deploying to production..."
            # Add your deployment logic for the production environment
          else
            echo "Unknown environment. Deployment aborted."
            exit 1
          fi
        env:
          API_KEY: ${{ secrets.NEW_GIT_SECRET }}
